# Generated by Django 3.0.8 on 2020-07-08 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnverifiedCouser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=15, null=True)),
                ('fullname', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.CharField(blank=True, max_length=30, null=True)),
                ('mobile', models.CharField(blank=True, max_length=10, null=True)),
                ('password', models.CharField(blank=True, max_length=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_email_verified', models.BooleanField(default=False)),
            ],
        ),
    ]
